### ISSUE TITLE
Operational failure

### ISSUE THREAD

**Issue by Aixpz** [thomthom/deep-pick#1]
Error: #<NoMethodError: undefined method `active_path=' for #<Sketchup::Model:0x000001b8243972f8>>
C:/Users/Administrator/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/tt_deep_pick/main.rb:65:in `onLButtonDown'

**Comment by thomthom** [comment]
This extension uses new feature added in SketchUp 2020 and will not work on older versions.

**Comment by Aixpz** [comment]
okay, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thomas Thomassen"<notifications@github.com&gt;; 
发送时间: 2020年4月4日(星期六) 下午3:28
收件人: "thomthom/deep-pick"<deep-pick@noreply.github.com&gt;; 
抄送: "黄金鸿"<1085803607@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thomthom/deep-pick] Operational failure (#1)





 
This extension uses new feature added in SketchUp 2020 and will not work on older versions.
